### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [Rayhane-mamah/Tacotron-2#196]
How to handle it?
`(tensorflow) E:\Python\Projekte\Tacotron-2>python train.py --checkpoint_interval 50
Using TensorFlow backend.

#############################################################

Tacotron Train

###########################################################

Checkpoint path: logs-Tacotron-2\taco_pretrained\tacotron_model.ckpt
Loading training data from: training_data/train.txt
Using model: Tacotron-2
Hyperparameters:
  allow_clipping_in_normalization: True
  attention_dim: 128
  attention_filters: 32
  attention_kernel: (31,)
  cin_channels: 80
  cleaners: english_cleaners
  clip_mels_length: True
  cross_entropy_pos_weight: 1
  cumulative_weights: True
  decoder_layers: 2
  decoder_lstm_units: 1024
  embedding_dim: 512
  enc_conv_channels: 512
  enc_conv_kernel_size: (5,)
  enc_conv_num_layers: 3
  encoder_lstm_units: 256
  fmax: 7600
  fmin: 75
  frame_shift_ms: None
  freq_axis_kernel_size: 3
  gate_channels: 512
  gin_channels: -1
  griffin_lim_iters: 60
  hop_size: 300
  input_type: raw
  kernel_size: 3
  layers: 30
  leaky_alpha: 0.4
  log_scale_min: -32.23619130191664
  log_scale_min_gauss: -16.11809565095832
  mask_decoder: False
  mask_encoder: False
  max_abs_value: 4.0
  max_iters: 1000
  max_mel_frames: 1300
  max_time_sec: None
  max_time_steps: 8000
  min_level_db: -100
  n_fft: 2048
  n_speakers: 5
  natural_eval: False
  normalize_for_wavenet: True
  num_freq: 1025
  num_mels: 80
  out_channels: 2
  outputs_per_step: 6
  postnet_channels: 512
  postnet_kernel_size: (5,)
  postnet_num_layers: 5
  power: 1.5
  predict_linear: True
  prenet_layers: [256, 256]
  quantize_channels: 65536
  ref_level_db: 20
  rescale: True
  rescaling_max: 0.999
  residual_channels: 512
  sample_rate: 16000
  signal_normalization: True
  silence_threshold: 2
  skip_out_channels: 256
  smoothing: False
  stacks: 3
  stop_at_any: True
  symmetric_mels: False
  tacotron_adam_beta1: 0.9
  tacotron_adam_beta2: 0.999
  tacotron_adam_epsilon: 1e-06
  tacotron_batch_size: 32
  tacotron_clip_gradients: False
  tacotron_data_random_state: 1234
  tacotron_decay_learning_rate: True
  tacotron_decay_rate: 0.4
  tacotron_decay_steps: 50000
  tacotron_dropout_rate: 0.5
  tacotron_final_learning_rate: 1e-05
  tacotron_initial_learning_rate: 0.001
  tacotron_random_seed: 5339
  tacotron_reg_weight: 1e-06
  tacotron_scale_regularization: True
  tacotron_start_decay: 50000
  tacotron_swap_with_cpu: False
  tacotron_synthesis_batch_size: 512
  tacotron_teacher_forcing_decay_alpha: 0.0
  tacotron_teacher_forcing_decay_steps: 280000
  tacotron_teacher_forcing_final_ratio: 0.0
  tacotron_teacher_forcing_init_ratio: 1.0
  tacotron_teacher_forcing_mode: constant
  tacotron_teacher_forcing_ratio: 1.0
  tacotron_teacher_forcing_start_decay: 10000
  tacotron_test_batches: 2
  tacotron_test_size: None
  tacotron_zoneout_rate: 0.1
  train_with_GTA: True
  trim_fft_size: 512
  trim_hop_size: 128
  trim_silence: True
  trim_top_db: 23
  upsample_conditional_features: True
  upsample_scales: [15, 20]
  use_bias: True
  use_lws: False
  use_speaker_embedding: True
  wavenet_adam_beta1: 0.9
  wavenet_adam_beta2: 0.999
  wavenet_adam_epsilon: 1e-08
  wavenet_batch_size: 4
  wavenet_data_random_state: 1234
  wavenet_dropout: 0.05
  wavenet_ema_decay: 0.9999
  wavenet_learning_rate: 0.001
  wavenet_random_seed: 5339
  wavenet_swap_with_cpu: False
  wavenet_synthesis_batch_size: 8
  wavenet_test_batches: None
  wavenet_test_size: 0.0441
  win_size: 1200
Loaded metadata for 321 examples (0.47 hours)
WARNING:tensorflow:From E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py:430: calling reverse_sequence (from tensorflow.python.ops.array_ops) with seq_dim is deprecated and will be removed in a future version.
Instructions for updating:
seq_dim is deprecated, use seq_axis instead
WARNING:tensorflow:From E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py:454: calling reverse_sequence (from tensorflow.python.ops.array_ops) with batch_dim is deprecated and will be removed in a future version.
Instructions for updating:
batch_dim is deprecated, use batch_axis instead
Initialized Tacotron model. Dimensions (? = dynamic shape):
  Train mode:               True
  Eval mode:                False
  GTA mode:                 False
  Synthesis mode:           False
  embedding:                (?, ?, 512)
  enc conv out:             (?, ?, 512)
  encoder out:              (?, ?, 512)
  decoder out:              (?, ?, 80)
  residual out:             (?, ?, 512)
  projected residual out:   (?, ?, 80)
  mel out:                  (?, ?, 80)
  linear out:               (?, ?, 1025)
  <stop_token> out:         (?, ?)
Initialized Tacotron model. Dimensions (? = dynamic shape):
  Train mode:               False
  Eval mode:                True
  GTA mode:                 False
  Synthesis mode:           False
  embedding:                (?, ?, 512)
  enc conv out:             (?, ?, 512)
  encoder out:              (?, ?, 512)
  decoder out:              (?, ?, 80)
  residual out:             (?, ?, 512)
  projected residual out:   (?, ?, 80)
  mel out:                  (?, ?, 80)
  linear out:               (?, ?, 1025)
  <stop_token> out:         (?, ?)
Tacotron training set to a maximum of 120000 steps
No model to load at logs-Tacotron-2\taco_pretrained

Generated 2 test batches of size 32 in 16.297 sec

Generated 32 train batches of size 32 in 51.081 sec
2018-09-12 12:26:58.870469: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 517.50MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-12 12:26:59.035325: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_driver.cc:903] failed to allocate 359.36M (376812288 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-09-12 12:27:09.509152: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 128.0KiB.  Current allocation summary follows.
2018-09-12 12:27:09.548647: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:279] ************************************x***************************************************************
2018-09-12 12:27:09.554243: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 32.0KiB.  Current allocation summary follows.
2018-09-12 12:27:09.563386: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at cwise_ops_common.cc:70 : Resource exhausted: OOM when allocating tensor with shape[32,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2018-09-12 12:27:09.577196: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:279] ************************************x***************************************************************
2018-09-12 12:27:09.581814: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at matmul_op.cc:474 : Resource exhausted: OOM when allocating tensor with shape[32,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2018-09-12 12:27:09.581848: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.83MiB.  Current allocation summary follows.
2018-09-12 12:27:09.610283: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:279] ************************************x***************************************************************
2018-09-12 12:27:09.614997: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at matmul_op.cc:474 : Resource exhausted: OOM when allocating tensor with shape[3744,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2018-09-12 12:27:19.615014: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 512.0KiB.  Current allocation summary follows.
2018-09-12 12:27:19.635164: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:279] ************************************x***************************************************************
2018-09-12 12:27:19.640626: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at matmul_op.cc:474 : Resource exhausted: OOM when allocating tensor with shape[32,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2018-09-12 12:27:29.649119: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 128.0KiB.  Current allocation summary follows.
2018-09-12 12:27:29.671502: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:279] ************************************x***************************************************************
2018-09-12 12:27:29.676738: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at random_op.cc:202 : Resource exhausted: OOM when allocating tensor with shape[32,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2018-09-12 12:27:39.683297: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 128.0KiB.  Current allocation summary follows.
2018-09-12 12:27:39.723261: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:279] ************************************x***************************************************************
2018-09-12 12:27:39.728994: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at cwise_ops_common.cc:70 : Resource exhausted: OOM when allocating tensor with shape[32,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Exiting due to exception: OOM when allocating tensor with shape[32,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/dropout_1/div = Mul[T=DT_FLOAT, _class=["loc:@model...ul_1/f_acc"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/sub_1, ConstantFolding/model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_1/dropout/div_recip)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/Shape/_579 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5326_...rdot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopConstantFolding/model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/ListDiff-folded-0/_5)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/dropout_1/div', defined at:
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 127, in main
    train(args, log_dir, hparams)
  File "train.py", line 52, in train
    checkpoint = tacotron_train(args, log_dir, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 308, in tacotron_train
    return train(log_dir, args, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 131, in train
    model, stats = model_train_mode(args, feeder, hparams, global_step)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 65, in model_train_mode
    is_training=True)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\tacotron.py", line 119, in initialize
    swap_memory=hp.tacotron_swap_with_cpu)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\seq2seq\python\ops\decoder.py", line 322, in dynamic_decode
    swap_memory=swap_memory)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3232, in while_loop
    return_same_structure)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2952, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2887, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\seq2seq\python\ops\decoder.py", line 265, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\custom_decoder.py", line 122, in step
    (cell_outputs, stop_token), cell_state = self._cell(inputs, state)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\Architecture_wrappers.py", line 175, in __call__
    LSTM_output, next_cell_state = self._cell(LSTM_input, state.cell_state)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\modules.py", line 286, in __call__
    return self._cell(inputs, states)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 222, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\layers\base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 1315, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\modules.py", line 138, in __call__
    h = (1 - self._zoneout_outputs) * tf.nn.dropout(new_h - prev_h, (1 - self._zoneout_outputs)) + prev_h
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2340, in dropout
    ret = math_ops.div(x, keep_prob) * binary_tensor
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1037, in div
    return _div_python2(x, y, name)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 981, in _div_python2
    return gen_math_ops.real_div(x, y, name=name)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6259, in real_div
    "RealDiv", x=x, y=y, name=name)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/dropout_1/div = Mul[T=DT_FLOAT, _class=["loc:@model...ul_1/f_acc"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/sub_1, ConstantFolding/model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_1/dropout/div_recip)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/Shape/_579 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5326_...rdot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopConstantFolding/model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/ListDiff-folded-0/_5)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/dropout_1/div = Mul[T=DT_FLOAT, _class=["loc:@model...ul_1/f_acc"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/sub_1, ConstantFolding/model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_1/dropout/div_recip)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/Shape/_579 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5326_...rdot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopConstantFolding/model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/ListDiff-folded-0/_5)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 175, in train
    step, loss, opt = sess.run([global_step, model.loss, model.optimize])
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/dropout_1/div = Mul[T=DT_FLOAT, _class=["loc:@model...ul_1/f_acc"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/sub_1, ConstantFolding/model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_1/dropout/div_recip)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/Shape/_579 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5326_...rdot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopConstantFolding/model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/ListDiff-folded-0/_5)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/dropout_1/div', defined at:
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 127, in main
    train(args, log_dir, hparams)
  File "train.py", line 52, in train
    checkpoint = tacotron_train(args, log_dir, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 308, in tacotron_train
    return train(log_dir, args, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 131, in train
    model, stats = model_train_mode(args, feeder, hparams, global_step)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 65, in model_train_mode
    is_training=True)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\tacotron.py", line 119, in initialize
    swap_memory=hp.tacotron_swap_with_cpu)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\seq2seq\python\ops\decoder.py", line 322, in dynamic_decode
    swap_memory=swap_memory)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3232, in while_loop
    return_same_structure)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2952, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2887, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\seq2seq\python\ops\decoder.py", line 265, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\custom_decoder.py", line 122, in step
    (cell_outputs, stop_token), cell_state = self._cell(inputs, state)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\Architecture_wrappers.py", line 175, in __call__
    LSTM_output, next_cell_state = self._cell(LSTM_input, state.cell_state)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\modules.py", line 286, in __call__
    return self._cell(inputs, states)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 222, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\layers\base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 1315, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "E:\Python\Projekte\Tacotron-2\tacotron\models\modules.py", line 138, in __call__
    h = (1 - self._zoneout_outputs) * tf.nn.dropout(new_h - prev_h, (1 - self._zoneout_outputs)) + prev_h
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2340, in dropout
    ret = math_ops.div(x, keep_prob) * binary_tensor
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1037, in div
    return _div_python2(x, y, name)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 981, in _div_python2
    return gen_math_ops.real_div(x, y, name=name)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6259, in real_div
    "RealDiv", x=x, y=y, name=name)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/dropout_1/div = Mul[T=DT_FLOAT, _class=["loc:@model...ul_1/f_acc"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_0/sub_1, ConstantFolding/model/inference/decoder/while/CustomDecoderStep/decoder_lstm/decoder_lstm/multi_rnn_cell/cell_1/dropout/div_recip)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/Shape/_579 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5326_...rdot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopConstantFolding/model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/location_features_layer/Tensordot/ListDiff-folded-0/_5)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

2018-09-12 12:27:40.104275: W T:\src\github\tensorflow\tensorflow\core\kernels\queue_base.cc:277] _1_datafeeder/input_queue: Skipping cancelled enqueue attempt with queue not closed
2018-09-12 12:27:40.108502: W T:\src\github\tensorflow\tensorflow\core\kernels\queue_base.cc:277] _0_datafeeder/eval_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread background:
Traceback (most recent call last):
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/eval_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](datafeeder/eval_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/token_targets_0_5, _arg_datafeeder/linear_targets_0_2, _arg_datafeeder/targets_lengths_0_4)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\tensorflow\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "E:\Anaconda\envs\tensorflow\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Python\Projekte\Tacotron-2\tacotron\feeder.py", line 174, in _enqueue_next_test_group
    self._session.run(self._eval_enqueue_op, feed_dict=feed_dict)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/eval_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](datafeeder/eval_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/token_targets_0_5, _arg_datafeeder/linear_targets_0_2, _arg_datafeeder/targets_lengths_0_4)]]

Caused by op 'datafeeder/eval_queue_enqueue', defined at:
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 127, in main
    train(args, log_dir, hparams)
  File "train.py", line 52, in train
    checkpoint = tacotron_train(args, log_dir, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 308, in tacotron_train
    return train(log_dir, args, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 127, in train
    feeder = Feeder(coord, input_path, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\feeder.py", line 97, in __init__
    self._eval_enqueue_op = eval_queue.enqueue(self._placeholders)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 339, in enqueue
    self._queue_ref, vals, name=scope)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4373, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

CancelledError (see above for traceback): Enqueue operation was cancelled
         [[Node: datafeeder/eval_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](datafeeder/eval_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/token_targets_0_5, _arg_datafeeder/linear_targets_0_2, _arg_datafeeder/targets_lengths_0_4)]]

Exception in thread background:
Traceback (most recent call last):
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/token_targets_0_5, _arg_datafeeder/linear_targets_0_2, _arg_datafeeder/targets_lengths_0_4)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\tensorflow\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "E:\Anaconda\envs\tensorflow\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Python\Projekte\Tacotron-2\tacotron\feeder.py", line 166, in _enqueue_next_train_group
    self._session.run(self._enqueue_op, feed_dict=feed_dict)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/token_targets_0_5, _arg_datafeeder/linear_targets_0_2, _arg_datafeeder/targets_lengths_0_4)]]

Caused by op 'datafeeder/input_queue_enqueue', defined at:
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 127, in main
    train(args, log_dir, hparams)
  File "train.py", line 52, in train
    checkpoint = tacotron_train(args, log_dir, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 308, in tacotron_train
    return train(log_dir, args, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\train.py", line 127, in train
    feeder = Feeder(coord, input_path, hparams)
  File "E:\Python\Projekte\Tacotron-2\tacotron\feeder.py", line 85, in __init__
    self._enqueue_op = queue.enqueue(self._placeholders)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 339, in enqueue
    self._queue_ref, vals, name=scope)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4373, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

CancelledError (see above for traceback): Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/token_targets_0_5, _arg_datafeeder/linear_targets_0_2, _arg_datafeeder/targets_lengths_0_4)]]

Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 127, in main
    train(args, log_dir, hparams)
  File "train.py", line 57, in train
    raise('Error occured while training Tacotron, Exiting!')
TypeError: exceptions must derive from BaseException`

**Comment by ErfolgreichCharismatisch** [comment]
I solved it by changing batch sizes:
```
tacotron_synthesis_batch_size = 8 * 16
tacotron_batch_size = 8
tacotron_test_batches = 40
```
Now I get 0.603 sec/step
